name: ${COMPOSE_PROJECT_NAME:-learn_python_test}
services:
  test_web:
    build: .
    volumes:
      - ./app:/work/app
      - ./tests:/work/tests
      - uv_tools_venv:/work/.venv
      - uv_tools_cache:/root/.cache/uv
      - ./htmlcov:/work/htmlcov
    ports:
      - "8001:8000"
    environment:
      PROFILE: test
#      DATABASE_URL: postgresql://postgres:postgres@test_db:5433/postgres
    depends_on:
      - test_db

  test_db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
 
volumes:
  postgres_data_test:
  uv_tools_venv:
  uv_tools_cache:
