name: CI - Pytest

on:
  push:
    branches: ["*", "!main"]
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. コードチェックアウト
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # 3. Dockerfileからキャッシュ付きでビルド
      - name: Build and Cache
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          tags: sample-app:1.0.0
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      # 4. docker compose upを実行(ビルドは不要)
      - name: test
#      - name: docker compose build & up
        run: |
          ./scripts/test.sh
# docker compose up -d
